import type { Metadata } from "next";
import localFont from 'next/font/local'

import { StyledComponentsRegistry } from "@/common/styled-components/registry";
import { QueryProvider } from "@/common/trpc/provider";
import { React95Provider } from "@/common/react95/provider";

import "./reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const galmuri11Font = localFont({
  src: [
    {
      path: './Galmuri11.woff2',
      weight: '400',
    },
    {
      path: './Galmuri11-Bold.woff2',
      weight: '600',
    },
  ],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={galmuri11Font.className}>
        <StyledComponentsRegistry>
          <React95Provider>
            <QueryProvider>
              {children}
            </QueryProvider>
          </React95Provider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
