name: Deploy Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Client
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: client/web
        run: npx @cloudflare/next-on-pages@1
        env:
          NEXT_PUBLIC_SERVER_API_HOST: ${{ vars.NEXT_PUBLIC_SERVER_API_HOST }}
          NEXT_PUBLIC_GITHUB_CLIENT_ID: ${{ vars.NEXT_PUBLIC_GITHUB_CLIENT_ID }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "client/web"
          command: pages deploy .vercel/output/static --project-name=gitcy
